"""One-time host/cluster setup required before a session runs:

  * A local container registry (Deployment + Service) the host pushes built
    images to and the node's containerd pulls from.
  * k3s /etc/rancher/k3s/registries.yaml allowing insecure pulls from
    localhost:5000. Not touched with sudo; when missing, the exact commands are
    printed for the user to run once.
  * mitmproxy CA cert + key on the host (~/.agent_uplink/mitm/), generated by a
    one-shot pod against the mitm image."""

from __future__ import annotations

import logging
import os
import shutil
import tempfile
import time
from datetime import datetime, timezone
from pathlib import Path

from .k8s import (
    Resources,
    apply_manifests,
    container_spec,
    deployment_manifest,
    hostpath_volume,
    kubectl,
    namespace_manifest,
    pod_manifest,
    pod_spec,
    service_manifest,
    wait_for_deployment_ready,
    wait_for_pod_succeeded,
)
from .process import run, run_command

LOGGER = logging.getLogger("agent-uplink")

REGISTRY_NAMESPACE = "agent-uplink-system"
REGISTRY_DEPLOYMENT = "registry"
REGISTRY_HOST_PORT = 5000
REGISTRY_HOSTPATH = "/var/lib/agent-uplink-registry"
REGISTRY_IMAGE_DEFAULT = "registry:2"
REGISTRY_PUSH_ENDPOINT = "localhost:5000"

K3S_REGISTRIES_PATH = Path("/etc/rancher/k3s/registries.yaml")


# ---------------------------------------------------------------------------
# registries.yaml check
# ---------------------------------------------------------------------------


_REGISTRIES_YAML_SETUP = """mirrors:
  "localhost:5000":
    endpoint:
      - "http://localhost:5000"
configs:
  "localhost:5000":
    tls:
      insecure_skip_verify: true
"""

_REGISTRIES_YAML_INSTRUCTIONS = f"""
One-time k3s setup is required so containerd can pull from the local registry.
Run these commands, then re-run agent-uplink:

  sudo mkdir -p /etc/rancher/k3s
  sudo tee {K3S_REGISTRIES_PATH} > /dev/null <<'EOF'
{_REGISTRIES_YAML_SETUP}EOF
  sudo systemctl restart k3s
"""


def check_registries_yaml() -> None:
    """Verify k3s knows about the local insecure registry; exit with the setup
    commands if not."""
    if not K3S_REGISTRIES_PATH.exists():
        raise SystemExit(
            f"{K3S_REGISTRIES_PATH} not found.\n" + _REGISTRIES_YAML_INSTRUCTIONS
        )
    content = K3S_REGISTRIES_PATH.read_text(encoding="utf-8")
    if "localhost:5000" not in content:
        raise SystemExit(
            f"{K3S_REGISTRIES_PATH} doesn't mention localhost:5000.\n"
            + _REGISTRIES_YAML_INSTRUCTIONS
        )


# ---------------------------------------------------------------------------
# Local registry deployment
# ---------------------------------------------------------------------------


def _registry_manifests(image: str) -> list[dict]:
    labels = {"app": "registry"}
    container = container_spec(
        name="registry",
        image=image,
        # Bind loopback only: with hostNetwork this still serves host pushes and
        # node containerd pulls, without exposing the registry on the LAN.
        env={
            "REGISTRY_HTTP_ADDR": "127.0.0.1:5000",
            "REGISTRY_STORAGE_DELETE_ENABLED": "true",
        },
        volume_mounts=[{"name": "data", "mountPath": "/var/lib/registry"}],
        resources=Resources(memory="256Mi", cpu="1"),
        ports=[
            {"containerPort": 5000, "hostPort": REGISTRY_HOST_PORT, "protocol": "TCP"}
        ],
    )
    spec = pod_spec(
        container=container,
        volumes=[
            hostpath_volume("data", REGISTRY_HOSTPATH, hp_type="DirectoryOrCreate")
        ],
        host_network=True,
        dns_policy="ClusterFirstWithHostNet",
    )
    return [
        namespace_manifest(REGISTRY_NAMESPACE),
        deployment_manifest(
            REGISTRY_DEPLOYMENT,
            REGISTRY_NAMESPACE,
            labels=labels,
            pod_spec=spec,
            strategy="Recreate",
        ),
        service_manifest(
            REGISTRY_DEPLOYMENT,
            REGISTRY_NAMESPACE,
            selector=labels,
            port=REGISTRY_HOST_PORT,
            target_port=5000,
        ),
    ]


def ensure_registry(image: str = REGISTRY_IMAGE_DEFAULT) -> None:
    """Apply the registry deployment (idempotent) and wait for readiness."""
    LOGGER.info("ensuring local registry deployment")
    apply_manifests(_registry_manifests(image))
    wait_for_deployment_ready(REGISTRY_NAMESPACE, REGISTRY_DEPLOYMENT, timeout=120)


# ---------------------------------------------------------------------------
# Build + push the agent image
# ---------------------------------------------------------------------------


AGENT_IMAGE_MAX_AGE_SECONDS = 86_400


def get_image_age_seconds(full_image: str) -> float | None:
    # Branch on the exit code (via run) so a missing image stays silent rather
    # than logging docker's "No such image" stderr as a warning.
    res = run(["docker", "image", "inspect", "-f", "{{.Created}}", full_image])
    out = res.stdout.strip()
    if not res.ok or not out:
        return None
    ts = out.rstrip("Z").split(".")[0]
    created = datetime.fromisoformat(ts).replace(tzinfo=timezone.utc)
    return (datetime.now(timezone.utc) - created).total_seconds()


def build_and_push_agent_image(
    image_repo: str, container_dir: Path, username: str, mitm_dir: Path,
    *, bust_cache: bool = False,
) -> str:
    """Build the agent image, push to the local registry, return its fully
    qualified reference."""
    full_image = f"{REGISTRY_PUSH_ENDPOINT}/{image_repo}:latest"

    build_args = [
        "--build-arg", f"USERNAME={username}",
        "--build-arg", f"USER_UID={os.getuid()}",
        "--build-arg", f"USER_GID={os.getgid()}",
    ]
    if bust_cache:
        build_args += ["--build-arg", f"CACHE_BUST={int(time.time())}"]

    # Build in a tempdir so the source tree is untouched and only the PUBLIC mitm
    # cert enters the context — the CA private key must never reach a layer.
    with tempfile.TemporaryDirectory(prefix="agent-uplink-build-") as td:
        ctx = Path(td)
        shutil.copytree(
            container_dir,
            ctx,
            dirs_exist_ok=True,
            ignore=shutil.ignore_patterns("certs", "__pycache__", "*.pyc"),
        )
        certs = ctx / "certs"
        certs.mkdir(exist_ok=True)
        shutil.copy2(
            mitm_dir / "mitmproxy-ca-cert.pem", certs / "mitmproxy-ca-cert.pem"
        )
        LOGGER.info(f"building {full_image}")
        run_command(
            ["docker", "build", *build_args, "-t", full_image, str(ctx)],
            stdout=None, stderr=None,
        )

    LOGGER.info(f"pushing {full_image}")
    run_command(["docker", "push", full_image], stdout=None, stderr=None)
    return full_image


# ---------------------------------------------------------------------------
# mitmproxy CA generation (one-shot pod with hostPath)
# ---------------------------------------------------------------------------


def ensure_mitm_certs(mitm_dir: Path, mitmproxy_image: str) -> bool:
    """Generate ~/.agent_uplink/mitm/* if missing. Returns True if certs were
    just generated (caller may need to rebuild the agent image)."""
    cert_file = mitm_dir / "mitmproxy-ca-cert.pem"
    if cert_file.exists():
        return False

    mitm_dir.mkdir(parents=True, exist_ok=True)
    LOGGER.info("generating mitmproxy CA via one-shot pod")
    uid, gid = os.getuid(), os.getgid()
    pod_name = f"agent-uplink-cert-gen-{os.getpid()}"
    container = container_spec(
        image=mitmproxy_image,
        command=["sh", "-c"],
        args=["exec mitmdump --set confdir=/certs --no-server -r /dev/null"],
        volume_mounts=[{"name": "certs", "mountPath": "/certs"}],
        security_context={"runAsUser": uid, "runAsGroup": gid},
        resources=Resources(memory="256Mi", cpu="500m"),
    )
    pod = pod_manifest(
        pod_name,
        "default",
        labels={"app": "agent-uplink-cert-gen"},
        spec=pod_spec(
            container=container,
            volumes=[
                hostpath_volume("certs", str(mitm_dir), hp_type="DirectoryOrCreate")
            ],
            restart_policy="Never",
        ),
    )
    try:
        apply_manifests([pod])
        wait_for_pod_succeeded("default", pod_name, timeout=120)
    finally:
        kubectl(
            "delete", "pod", pod_name, "-n", "default",
            "--wait=false", "--ignore-not-found=true", raise_error=False,
        )
    if not cert_file.exists():
        raise RuntimeError(
            f"mitm cert generation didn't produce {cert_file}; check pod logs"
        )
    return True
