"""One-time host/cluster setup that has to be in place before a session runs.

Three pieces:
  * Local container registry (a long-lived Deployment + Service) that the host
    pushes built images to via `docker push localhost:5000/...` and that
    containerd pulls from on the same node.
  * k3s /etc/rancher/k3s/registries.yaml allowing insecure (HTTP) pulls from
    localhost:5000. We do NOT touch this file with sudo from agent-uplink;
    when it's missing, we print the exact shell commands and exit so the user
    runs them once.
  * mitmproxy CA cert + key on the host (~/.agent_uplink/mitm/), generated by
    a one-shot pod against the mitm image with a hostPath mount.
"""

from __future__ import annotations

import logging
import os
import shutil
import time
from pathlib import Path

from .k8s import (
    apply_manifests,
    deployment_manifest,
    hostpath_volume,
    kubectl,
    namespace_exists,
    namespace_manifest,
    pod_manifest,
    service_manifest,
    wait_for_deployment_ready,
    wait_for_pod_succeeded,
)
from .process import run_command

LOGGER = logging.getLogger("agent-uplink")

REGISTRY_NAMESPACE = "agent-uplink-system"
REGISTRY_DEPLOYMENT = "registry"
REGISTRY_HOST_PORT = 5000
REGISTRY_HOSTPATH = "/var/lib/agent-uplink-registry"
REGISTRY_IMAGE_DEFAULT = "registry:2"
REGISTRY_PUSH_ENDPOINT = "localhost:5000"

K3S_REGISTRIES_PATH = Path("/etc/rancher/k3s/registries.yaml")


# ---------------------------------------------------------------------------
# registries.yaml check
# ---------------------------------------------------------------------------


_REGISTRIES_YAML_SETUP = """mirrors:
  "localhost:5000":
    endpoint:
      - "http://localhost:5000"
configs:
  "localhost:5000":
    tls:
      insecure_skip_verify: true
"""

_REGISTRIES_YAML_INSTRUCTIONS = f"""
One-time k3s setup is required so containerd can pull from the local registry.
Run these commands, then re-run agent-uplink:

  sudo mkdir -p /etc/rancher/k3s
  sudo tee {K3S_REGISTRIES_PATH} > /dev/null <<'EOF'
{_REGISTRIES_YAML_SETUP}EOF
  sudo systemctl restart k3s
"""


def check_registries_yaml() -> None:
    """Verify k3s knows about the local insecure registry. Exit with a
    helpful error if not."""
    if not K3S_REGISTRIES_PATH.exists():
        raise SystemExit(
            f"{K3S_REGISTRIES_PATH} not found.\n" + _REGISTRIES_YAML_INSTRUCTIONS
        )
    content = K3S_REGISTRIES_PATH.read_text(encoding="utf-8")
    if "localhost:5000" not in content:
        raise SystemExit(
            f"{K3S_REGISTRIES_PATH} doesn't mention localhost:5000.\n"
            + _REGISTRIES_YAML_INSTRUCTIONS
        )


# ---------------------------------------------------------------------------
# Local registry deployment
# ---------------------------------------------------------------------------


def _registry_manifests(image: str) -> list[dict]:
    labels = {"app": "registry"}
    pod_spec: dict = {
        "hostNetwork": True,
        "dnsPolicy": "ClusterFirstWithHostNet",
        "containers": [
            {
                "name": "registry",
                "image": image,
                "imagePullPolicy": "IfNotPresent",
                "ports": [
                    {
                        "containerPort": 5000,
                        "hostPort": REGISTRY_HOST_PORT,
                        "protocol": "TCP",
                    }
                ],
                "env": [
                    {"name": "REGISTRY_HTTP_ADDR", "value": "0.0.0.0:5000"},
                    {
                        "name": "REGISTRY_STORAGE_DELETE_ENABLED",
                        "value": "true",
                    },
                ],
                "volumeMounts": [{"name": "data", "mountPath": "/var/lib/registry"}],
                "resources": {"limits": {"memory": "256Mi", "cpu": "1"}},
            }
        ],
        "volumes": [
            hostpath_volume(
                "data", REGISTRY_HOSTPATH, hp_type="DirectoryOrCreate"
            )
        ],
    }
    return [
        namespace_manifest(REGISTRY_NAMESPACE),
        deployment_manifest(
            REGISTRY_DEPLOYMENT,
            REGISTRY_NAMESPACE,
            labels=labels,
            pod_spec=pod_spec,
        ),
        service_manifest(
            REGISTRY_DEPLOYMENT,
            REGISTRY_NAMESPACE,
            selector=labels,
            port=REGISTRY_HOST_PORT,
            target_port=5000,
        ),
    ]


def ensure_registry(image: str = REGISTRY_IMAGE_DEFAULT) -> None:
    """Apply the registry deployment (idempotent) and wait for readiness."""
    LOGGER.info("ensuring local registry deployment")
    apply_manifests(_registry_manifests(image))
    wait_for_deployment_ready(REGISTRY_NAMESPACE, REGISTRY_DEPLOYMENT, timeout=120)


# ---------------------------------------------------------------------------
# Build + push the agent image
# ---------------------------------------------------------------------------


AGENT_IMAGE_MAX_AGE_SECONDS = 86_400


def get_image_age_seconds(full_image: str) -> float | None:
    out = run_command(
        ["docker", "image", "inspect", "-f", "{{.Created}}", full_image],
        raise_error=False,
    ).strip()
    if not out:
        return None
    from datetime import datetime, timezone
    ts = out.rstrip("Z").split(".")[0]
    created = datetime.fromisoformat(ts).replace(tzinfo=timezone.utc)
    return (datetime.now(timezone.utc) - created).total_seconds()


def build_and_push_agent_image(
    image_repo: str, container_dir: Path, username: str, mitm_dir: Path,
    *, force_rebuild: bool = False,
) -> str:
    """Build the agent image via docker, push to the local registry, return
    the fully qualified image reference."""
    full_image = f"{REGISTRY_PUSH_ENDPOINT}/{image_repo}:latest"

    # Copy mitm CA into the build context so the Dockerfile's COPY succeeds.
    shutil.copytree(mitm_dir, container_dir / "certs", dirs_exist_ok=True)

    LOGGER.info(f"building {full_image}")
    build_args = [
        "--build-arg", f"USERNAME={username}",
        "--build-arg", f"USER_UID={os.getuid()}",
        "--build-arg", f"USER_GID={os.getgid()}",
    ]
    if force_rebuild:
        build_args += ["--build-arg", f"CACHE_BUST={int(time.time())}"]
    run_command(
        ["docker", "build", *build_args, "-t", full_image, str(container_dir)],
        stdout=None, stderr=None,
    )
    LOGGER.info(f"pushing {full_image}")
    run_command(["docker", "push", full_image], stdout=None, stderr=None)
    return full_image


# ---------------------------------------------------------------------------
# mitmproxy CA generation (one-shot pod with hostPath)
# ---------------------------------------------------------------------------


def ensure_mitm_certs(mitm_dir: Path, mitmproxy_image: str) -> bool:
    """Generate ~/.agent_uplink/mitm/* if missing. Returns True if certs were
    just generated (caller may need to rebuild the agent image)."""
    cert_file = mitm_dir / "mitmproxy-ca-cert.pem"
    if cert_file.exists():
        return False

    mitm_dir.mkdir(parents=True, exist_ok=True)
    LOGGER.info("generating mitmproxy CA via one-shot pod")
    uid, gid = os.getuid(), os.getgid()
    pod_name = f"agent-uplink-cert-gen-{os.getpid()}"
    pod = pod_manifest(
        name=pod_name,
        namespace="default",
        labels={"app": "agent-uplink-cert-gen"},
        image=mitmproxy_image,
        command=["sh", "-c"],
        args=["exec mitmdump --set confdir=/certs --no-server -r /dev/null"],
        volumes=[hostpath_volume("certs", str(mitm_dir), hp_type="DirectoryOrCreate")],
        volume_mounts=[{"name": "certs", "mountPath": "/certs"}],
        container_security_context={"runAsUser": uid, "runAsGroup": gid},
        restart_policy="Never",
        memory="256Mi",
        cpu="500m",
    )
    try:
        apply_manifests([pod])
        wait_for_pod_succeeded("default", pod_name, timeout=120)
    finally:
        kubectl(
            "delete", "pod", pod_name, "-n", "default",
            "--wait=false", "--ignore-not-found=true", raise_error=False,
        )
    if not cert_file.exists():
        raise RuntimeError(
            f"mitm cert generation didn't produce {cert_file}; check pod logs"
        )
    return True


# ---------------------------------------------------------------------------
# Misc
# ---------------------------------------------------------------------------


def ensure_registry_namespace() -> None:
    """Apply just the registry namespace (used early so the deployment apply
    has somewhere to land)."""
    if not namespace_exists(REGISTRY_NAMESPACE):
        apply_manifests([namespace_manifest(REGISTRY_NAMESPACE)])
